services:
  tarantool:
    image: tarantool/tarantool:3.2
    container_name: kv-tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua:ro
      - tarantool_data:/var/lib/tarantool
    command: ["tarantool", "/opt/tarantool/init.lua"]

volumes:
  tarantool_data: